FROM ruby

MAINTAINER jcrisp <justcrisp@outlook.com>

RUN apt-get update -y && apt-get install -y build-essential libpq-dev nodejs sqlite3

ONBUILD COPY app /opt/app
ONBUILD WORKDIR /opt/app

ONBUILD EXPOSE 3000
ONBUILD RUN bundle install
ONBUILD RUN  rake db:migrate
ONBUILD RUN rake db:seed

# BUILD
# docker build -t ft-rails:on-build
# docker build -t ex02
# docker run -it --rm -p 3000:3000 ex02
